### ISSUE TITLE
constraining multilingual attributes

### ISSUE THREAD

**Issue by pchampin** [w3c/shacl#14]
During a [workshop on Distrbuted Knowledge Graph metadata](https://cost-dkg.github.io/metadata4dkg2022/), the need emerged to constrain a property to contain:
- one-to-many language tagged strings, but 
- at most one value per language tag.

Therefore this would be allowed
```
<> dct:description "My Knowledge Graph"@en, "Mon graphe de connaissances"@fr.
```
would be valid, but
```
<> dct:description "My Knowledge Graph"@en, "My KG"@en.
```
would not.

Is it possible to express that kind of constraint using SHACL?

**Comment by afs** [comment]
[sh:uniqueLang](https://www.w3.org/TR/shacl/#UniqueLangConstraintComponent)

**Comment by pchampin** [comment]
thanks. Don't know why I didn't spot that...
