### ISSUE TITLE
Does shacl provide validation for data in jsonld 1.1 version

### ISSUE THREAD

**Issue by sanuann** [w3c/shacl#2]
I have a data graph in jsonld 1.1 version with the context mentioning the version explicitly. When I write a shape graph for the data, it gives error. But when I remove the @version key from the context, the validation works.
How can I write shapes for data expressed in jsonld 1.1 format?

**Comment by VladimirAlexiev** [comment]
@sanuann SHACL is independent of any RDF format, including JSONLD 1.0 or 1.1.
Can you give specific examples of the problem you experienced?

**Comment by HolgerKnublauch** [comment]
In preparation for a potential future SHACL WG I would like to close GitHub issues that were mainly just questions. Please reopen if you disagree.
