### ISSUE TITLE
shaclc: choose diagramming tool

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/shacl#54]
@jeswr 
I assume that the spec will include:
- shaclc EBNF as text (in an annex)
- shaclc syntax diagrams

Which tool to use? For me the choice is clear :-)
- https://rr.red-dove.com/ui is i think the best tool.
  - here are some examples https://github.com/VladimirAlexiev/grammar-diagrams#shaclc
  - pro: it makes links between productions
  - pro: makes a single HTML file that embeds the SVG diagrams and the links between them
  - https://github.com/GuntherRademacher/ebnf-convert was used for a local install to make the diagrams of the candidate grammars
- https://plantuml.com/ebnf is an alternative, but:
  - cons: it supports (ISO?) EBNF not W3C-style EBNF
  - cons: it makes one monolithic diagram, with no links between productions (even in SVG)
  - pro: supports a compact style ("Compacted mode"), see https://plantuml.com/ebnf#pre3a77433986c471ef7119127d127a9927

Let's think how to integrate the diagrams into the spec
- as a minimum, the diagrams can be published as a separate file
- or they can be embedded as another annex
- as a maximum, we can link to particular productions from the text of the spec

**Comment by jeswr** [comment]
You make a good case for https://rr.red-dove.com/ui - I'm in support of using that tool. My personal preference would be to have a separate page with all of the Linked SVG's + links to particular productions / svg from the core text .

**Comment by VladimirAlexiev** [comment]
I agree: RR in a separate annex, and links from spec to annex.
