### ISSUE TITLE
Adding timestamp on validation reports

### ISSUE THREAD

**Issue by jerdebsp** [w3c/shacl#56]
We have a use case where we need to store the validation reports in a store. Would it be useful to add a timestamp to each sh:ValidationReport?

**Comment by HolgerKnublauch** [comment]
There is no dedicated property for that, but could you simply add that triple in your own code?

**Comment by jerdebsp** [comment]
Yes that is possible, however, if we're using say SHACL API or PySHACL as part of a pipeline, then it makes it a bit messy (some shell script or executing a SPARQL update). I guess having it as part of the schema it would automatically be available, and would be easier when there are parallel processes as well

**Comment by HolgerKnublauch** [comment]
The problem that I see is that different audiences will prefer to have different properties here. For example, who ran it, against which data graph, with which shapes graph, include valid/invalid/warnings etc. There is an infinite number of such metadata properties, and an API would need to be defined to select them. This is no trivial task. Even the time stamp could be different for each result, if it runs for a few seconds.

**Comment by jimkont** [comment]
a small extension on [annotation properties (in Shacl AF)](https://www.w3.org/TR/shacl-af/#sparql-constraints-annotations) should be able to cover custom triple annotations on results, outside of SHACL-SPARQL

**Comment by jerdebsp** [comment]
Lovely Dimitris. Had no clue about it. Thanks!
