### ISSUE TITLE
Typo/Bug in current specs

### ISSUE THREAD

**Issue by jerdebsp** [w3c/shacl#57]
In the current specs, in section 1.4 - Example (https://www.w3.org/TR/shacl/#shacl-example), the example makes use of `sh:RegexConstraintComponent` and further down, in the description it mentions `sh:regex`.

I think that should be `sh:PatternConstraintComponent` and `sh:pattern`.

```
	[	a sh:ValidationResult ;
		sh:resultSeverity sh:Violation ;
		sh:focusNode ex:Alice ;
		sh:resultPath ex:ssn ;
		sh:value "987-65-432A" ;
		sh:sourceConstraintComponent sh:RegexConstraintComponent ;
		sh:sourceShape ... blank node _:b1 on ex:ssn above ... ;

```

and

> The [validation results](https://www.w3.org/TR/shacl/#dfn-validation-results) are enclosed in a [validation report](https://www.w3.org/TR/shacl/#dfn-validation-report). The first [validation result](https://www.w3.org/TR/shacl/#dfn-validation-results) is produced because ex:Alice has a [value](https://www.w3.org/TR/shacl/#dfn-value) for ex:ssn that does not match the regular expression specified by the property sh:regex.

**Comment by HolgerKnublauch** [comment]
Good catch!

**Comment by jerdebsp** [comment]
Doing a pull request right now

**Comment by HolgerKnublauch** [comment]
Thanks, merged in.
