### ISSUE TITLE
Maintain updated list of SHACL implementations

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/shacl#78]
The official Implementation Report https://w3c.github.io/data-shapes/data-shapes-test-suite/ is 5 years old and badly obsolete. https://github.com/validatingrdf/validatingrdf.github.io/issues/14 collected
https://github.com/validatingrdf/validatingrdf.github.io/wiki/Updated-list-of-implementations that is perhaps 3 years newer has these rubrics:
- ShEx validators
- SHACL validators
- Shapes (collections)
- Shape Conversion tools
- Shape Editors, Visualizations
- Declarative UIs

But it has several defects:
- It's quite out of the way and hard to find. It would be a lot more visible and sustainable if it was adopted by the W3C SHACL CG and listed amongst its resources, eg in the Implementation Report
- It is now out of date. I think there are 5-6 newer SHACL implementations missing:
  - Jena
  - https://github.com/zazuko/rdf-validate-shacl and https://shacl-playground.zazuko.com/
  - https://github.com/rdf-ext/shacl-engine
  - https://gitlab.com/allotrope-open-source/shape-editor, which is both an editor and (I think) a validator, and adds some extra features: https://github.com/w3c/shacl/issues/74
  - https://github.com/DataTreehouse/maplib (the SHACL is still private, to be released shortly, claimed to be very performant)
- lacks a couple from https://github.com/semantalytics/awesome-semantic-web#shacl-implementations
- It is not completely filled out (latest version and update date are missing)
- I lacks SHACL Compact implementations, but we have a complete list here: https://github.com/VladimirAlexiev/shacl/blob/shaclc-add-goals-implementations/shacl-compact-syntax/scope.md#implementations
- It is not rendered in a readable way (full width, ability to sort)
- It is a bit hard to contribute to. Maybe it's better to switch to a google sheet?

**Comment by tpluscode** [comment]
> It is a bit hard to contribute to. Maybe it's better to switch to a google sheet?

I wanted to mention an "awesome" list. Maybe we could simply have an "Awesome SHACL" in a repo. Easy to maintain, easy to contribute

**Comment by HolgerKnublauch** [comment]
Yeah the original impl report was obviously only created to pass the W3C process for SHACL 1.0. Yes it would be great to have a better, living document somewhere.

**Comment by VladimirAlexiev** [comment]
@tpluscode I like Awesome lists, as soon as we agree to add basic info like latest version and last update date, link to Playground implementation (if any).
- There are a few implementations mentioned at https://github.com/semantalytics/awesome-semantic-web#shacl-implementations
- But that list is very incomplete, so I made a PR https://github.com/semantalytics/awesome-semantic-web/pull/264 to add a link to here

**Comment by VladimirAlexiev** [comment]
Turns out that I posted an internal task 3.5y ago. Here are details from that task. Why:
- Updated-list-of-implementations was based on the validatingrdf and updates many times, and now it’s the definitive list on Shapes
- Formatting it as an "awesome" list will make it a lot more popular
- "awesome" is not some stupid marketing slogan, it's a movement to provide excellent lists of resources and surveys on a certain topic.

Task
- Make a git folder, eg https://github.com/w3c/data-shapes/awesome-semantic-shapes
  - Note1: I had https://github.com/Ontotext-AD/awesome-semantic-shapes but it's better to use a neutral location.
  - Note2: but I think it needs to be a top-level project to fit the "awesome" list of lists format
  - Note3: it will be about both SHACL and SHEX, so shouldn't be under https://github.com/w3c/shacl/
- take https://github.com/validatingrdf/validatingrdf.github.io/wiki/Updated-list-of-implementations and convert it to the "awesome" format (see below)
- add implementations including validators, shape editors, shape generators, visualization 
- Add resources: the book, tutorials, presentations:
- integrate it properly into the "awesome" list of lists https://github.com/sindresorhus/awesome = https://awesome.re/ (see tech details below)
- check whether it appears ok in https://awesomelists.top/ (warning: https://github.com/sindresorhus/awesome/issues/1976#issuecomment-813352771 hints that site is not being updated)

Sources:
- the validatingrdf book
- items from https://github.com/semantalytics/awesome-semantic-web/#shacl-implementations 
- search on github for "shacl" and "shex"
- https://www.validatingrdf.com/tutorial/swat4hcls22/slides/RDF_ShEx_EntitySchemas_Labra.pdf slide 48 of 140:
  - ShEx implementations : shex.js: Javascript, Apache Jena ShEx: Java, shex-s: Scala (Jena/RDF4j), PyShEx: Python, shex-java: Java, Ruby-ShEx: Ruby, ShEx-ex: Elixir 
  - Online demos & playgrounds: ShEx-simple RDFShape ShEx-Java ShExValidata Wikishape
- Onto Slack channel #shapes

Tech notes
- https://awesomelists.top/ has collected an amazing wealth of such lists. It's driven by https://github.com/sindresorhus/awesome and strict content format rules that allow that app to parse the lists:
- https://github.com/dar5hak/generator-awesome-list to generate a skeleton for a list
- https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
- https://github.com/sindresorhus/awesome/blob/main/contributing.md
- https://github.com/sindresorhus/awesome/blob/main/create-list.md
- https://github.com/sindresorhus/awesome-lint to validate a list

**Comment by VladimirAlexiev** [comment]
@tpluscode can you check https://github.com/sindresorhus/awesome to see whether an Awesome list should be in its own repo?

@tpluscode and @HolgerKnublauch what'd be a good location for our awesome list? Maybe https://github.com/w3c/data-shapes/awesome-semantic-shapes ?

**Comment by labra** [comment]
I really like the idea of an awesome-semantic-shapes repo and I think if you want to include resources about SHACL and ShEx, it would make sense to call it _semantic shapes_ so it could include resource from both. 

I would be happy to contribute or help maintaining it as well.

**Comment by amivanoff** [comment]
Maybe its better to go with https://github.com/w3c/awesome-semantic-shapes? (If w3c allow it on a top level.)
There are some advantages in separate repo:
 - Only one responsibility per repository -- easier to contribute from a broader community:
   - no need to clone spec stuff
   - simple repository folders structure
   - no 'not awesome' spec issues (sorry, guys 😊)
   - no 'not awesome' other pull requests
 - More top-level visible 'awesomness'
   - for the W3C if there will be more repos like https://github.com/w3c/awesome-XXX )))
   - for the Semantic Web (Linked Data) community if there will be more repos like https://github.com/w3c/awesome-semantic-XXX )))
 - 'awesomness list' lifecycle (continuous and forever thing, should gather github stars from all versions of spec, as much as possible) decoupled from spec lifecycle (chunked by spec versions)

**Comment by amivanoff** [comment]
Another option is to create a vendor-neutral GitHub organization like 'swcommons' or something similar, separate from w3c. An organizaion, open to all representatives from SW and related vendors and established experts.
Something like https://github.com/mlcommons, but maybe without a non-profit org status.

Then it will be https://github.com/swcommons/awesome-semantic-shapes.

**Comment by afs** [comment]
A working group or a community group can have several repos - the RDF-star working group has one repo per document.

The charter for the SHACL-WG could include the possibility of becoming a "maintenance and new feature" on-going working group after the charter for new work has been completed. This enables errata to be handled in a timely manner.

SHACL issue : https://github.com/w3c/shacl/issues/80

It may be possible to put community reviewed, non-specification, material under that group.

It could also be under a Community Group (this repo is owned by the SHACL Community Group; other community groups can be created). The [RDF tests] maintenance (https://w3c.github.io/rdf-tests/) works on this basis.

**Comment by VladimirAlexiev** [comment]
@pchampin or @iherman can you please make a repo
https://github.com/w3c/awesome-semantic-shapes ?
Give committer (maintainer?) rights to @VladimirAlexiev @labra @HolgerKnublauch @afs.

@amivanoff could you please take a first stab at it? Make the structure as per `awesomelist` and add sections as per my above comment and the "updated list".

Then it will be much easier for me to add content.

**Comment by ianbjacobs** [comment]
Created the repo:  https://github.com/w3c-cg/awesome-semantic-shapes

**Comment by amivanoff** [comment]
The default repository stub of [w3c-cg/awesome-semantic-shapes](https://github.com/w3c-cg/awesome-semantic-shapes) has two licenses:
* [W3C Software and Document License](https://www.w3.org/copyright/software-license/) -- for all reports
* [W3C 3-clause BSD License](https://www.w3.org/copyright/3-clause-bsd-license-2008/) -- for Test Suites

It turns out, [pull request constraints](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md) in the "awesome list of awesomes" in the sindresorhus/awesome repo has these license statements, which prevents us from adding awesome-semantic-shapes repository to this list after its completion:
* We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work.
* A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org/).

Is it possible to do all of this for the w3c-cg/awesome-semantic-shapes repository?
* To dump BSD for Test Suites, because there will be no Test Suites or any other source code?
* To use for the Readme file, Issues and Pull requests [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/) or any other of CC license instead of W3C Software and Document License?

**Comment by amivanoff** [comment]
Also there is another constraint in [w3c-cg/awesome-semantic-shapes](https://github.com/w3c-cg/awesome-semantic-shapes) (if I understand it correctly) that a pull request author(s) should be strictly from the SHACL Community Group.

It is different from typical process in "awesomes" community where anyone could propose a pull request, but maintainers desides what to accept.

**Comment by amivanoff** [comment]
Sorry for mis-posting, I moved questions to a separate issue
* w3c-cg/awesome-semantic-shapes#5

**Comment by VladimirAlexiev** [comment]
The final location is https://github.com/w3c-cg/awesome-semantic-shapes and it's looking pretty good!
