### ISSUE TITLE
How to decide whether a given graph is a (valid) shapes graph

### ISSUE THREAD

**Issue by stigbd** [w3c/shacl#9]
We are currently implementing a SHACL based validator where the user may supply his own shapes graph. Before doing the actual validation, our service tries first to validate if the given shapes graph in fact _is_ a shapes graph,  and next whether it is a valid one.

The last part of the problem is relatively straightforward, as we are planning to run a set of "meta shacl" shapes on the given shapes graph itself.

Our problem starts when this "meta-validation" process says no violations when the supplied graph in fact does not contain any shacl shapes. 

Given the definition of a shapes graphs as 
> A shapes graph is an RDF graph containing zero or more shapes that is passed into a SHACL validation process so that a data graph can be validated against the shapes.
(from https://www.w3.org/TR/shacl/#shapes-graph)

it is not obvious to us how we should decide whether something is a shapes graph, since a graph containing 0 shapes also is a shapes graph according to the above definition.

We would greatly appreciate advice on how we should approach this.

**Comment by HolgerKnublauch** [comment]
In preparation for a potential future SHACL WG I would like to close GitHub issues that were mainly just questions.

Sorry this one here didn't get responses but I guess after 3 years the question is probably outdated. The Discord server or mailing list are arguably better ways to ask such questions.
